name: Linux

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout CI sample
      uses: actions/checkout@v6
      with:
        ref: 'ci-sample'
    - name: Install PostgresQL
      run: |
        sudo apt install postgresql
        sudo service postgresql start
        sudo -u postgres createuser --superuser runner
        createdb odoo
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-26.05
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Set up git
      run: |
        git config --global user.name "Wax CI Job"
        git config --global user.email "wax@wax.xxx"
    - name: Enter shell
      run: nix develop .
    - name: Build Wax
      run: nix develop . --command build-dev
