name: Linux

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout CI sample
      uses: actions/checkout@v6
      with:
        ref: 'ci-sample'
    - name: Install Nix
      run: sudo apt install --no-install-recommends -y nix-bin
    - name: Enter shell
      run: nix develop --extra-experimental-features 'nix-command flakes' .
    - name: Build Wax
      run: nix develop --extra-experimental-features 'nix-command flakes' . --command "build-dev"
    - name: Run Odoo
      run: |
        createdb odoo
        nix develop --extra-experimental-features 'nix-command flakes' . --command "run --stop-after-init -i base"
